// =====================================================
// AGRILINK SEWA - CENTRALIZED 13-LANGUAGE MULTILINGUAL SYSTEM
// Full support for 13 major Indian languages with Urdu RTL
// =====================================================

export const supportedLanguages = [
    { code: "en", label: "English" },
    { code: "hi", label: "हिन्दी (Hindi)" },
    { code: "gu", label: "ગુજરાતી (Gujarati)" },
    { code: "mr", label: "मराठी (Marathi)" },
    { code: "bn", label: "বাংলা (Bengali)" },
    { code: "ta", label: "தமிழ் (Tamil)" },
    { code: "te", label: "తెలుగు (Telugu)" },
    { code: "kn", label: "ಕನ್ನಡ (Kannada)" },
    { code: "ml", label: "മലയാളം (Malayalam)" },
    { code: "pa", label: "ਪੰਜਾਬੀ (Punjabi)" },
    { code: "or", label: "ଓଡ଼ିଆ (Odia)" },
    { code: "as", label: "অসমীয়া (Assamese)" },
    { code: "ur", label: "اردو (Urdu)" }
];

export const translations = {
  "en": {
    "brand": "AGRILINK SEWA",
    "brandSub": "National Digital Agriculture Procurement & Logistics Network",
    "govIndia": "GOVERNMENT OF INDIA",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "Logout",
    "login": "Login",
    "register": "Register",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "Welcome",
    "live": "LIVE",
    "roleFarmer": "Kisan (Farmer)",
    "roleTransporter": "Logistics Partner (Transporter)",
    "roleOperator": "Mandi Operator (Official)",
    "farmerPortal": "National Farmer Portal",
    "transporterPortal": "TRANSPORTER MANAGEMENT SYSTEM",
    "operatorPortal": "MANDI OPERATOR PORTAL",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "Destination Mandi",
    "mandiName": "Mandi Name",
    "tokenId": "Token ID",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "Scan at weighing bridge",
    "printPass": "Print Pass",
    "printTicket": "Print Ticket",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "Need Transportation Support for this harvest?",
    "cropName": "Crop Name",
    "estimatedQuantity": "Estimated Quantity (Quintals)",
    "openStatus": "OPEN",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "VERIFIED FARMER",
    "pendingVerifBadge": "VERIFICATION PENDING",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "Token No.",
    "cropQty": "Crop (Qty)",
    "status": "Status",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "Approve",
    "reject": "Reject",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "Start Trip",
    "reachedMandi": "Reached Mandi",
    "completeTrip": "Complete Trip",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "hi": {
    "brand": "एग्रीलिंक सेवा",
    "brandSub": "राष्ट्रीय डिजिटल कृषि खरीद एवं रसद समन्वय प्रणाली",
    "govIndia": "भारत सरकार",
    "govDept": "उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय",
    "nicCredit": "राष्ट्रीय सूचना विज्ञान केंद्र (NIC) द्वारा डिजाइन और विकसित",
    "logout": "लॉग आउट",
    "login": "लॉग इन",
    "register": "पंजीकरण",
    "secureLogin": "सुरक्षित लॉगिन",
    "authorizedLogin": "अधिकृत लॉगिन",
    "citizenReg": "नागरिक पंजीकरण",
    "welcome": "स्वागत है",
    "live": "लाइव",
    "roleFarmer": "किसान (Kisan)",
    "roleTransporter": "रसद भागीदार (Transporter)",
    "roleOperator": "मंडी अधिकारी (Operator)",
    "farmerPortal": "राष्ट्रीय किसान पोर्टल",
    "transporterPortal": "ट्रांसपोर्टر प्रबंधन प्रणाली",
    "operatorPortal": "मंडी ऑपरेटर पोर्टल",
    "operatorSub": "गेट और कतार प्रबंधन प्रणाली",
    "farmerDashboardTitle": "खरीद डैशबोर्ड",
    "farmerDashboardSub": "अपनी फसल जमा करने का समय निर्धारित करें और डिजिटल गेट पास प्रबंधित करें।",
    "activeRegion": "सक्रिय क्षेत्र",
    "nearbyCenters": "निकटतम खरीद केंद्र",
    "bookingLockedMsg": "उपज जमा होने तक डैशबोर्ड लॉक है",
    "validPass": "वैध पास",
    "destinationMandi": "गंतव्य मंडी",
    "mandiName": "मंडी का नाम",
    "tokenId": "टोकन संख्या",
    "farmerName": "किसान का नाम",
    "reportingDate": "रिपोर्टिंग तिथि",
    "assignedTimeSlot": "निर्धारित समय स्लॉट",
    "scanAtBridge": "धर्मकांटे पर स्कैन करें",
    "printPass": "पास प्रिंट करें",
    "printTicket": "टिकट प्रिंट करें",
    "returnDashboard": "डैशबोर्ड पर लौटें",
    "bookingSlotFor": "स्लॉट बुकिंग केंद्र",
    "continuousSlotsSub": "15-मिनट अंतराल",
    "reviewConfirm": "अनुरोध की समीक्षा और पुष्टि",
    "citizenDetailsVerif": "नागरिक विवरण सत्यापन",
    "registeredPin": "पंजीकृत पिन कोड",
    "arrivalTimeSlot": "आगमन समय स्लॉट",
    "confirmSyncBtn": "पुष्टि करें और डेटाबेस में सिंक करें",
    "bookingSuccessTitle": "बुकिंग सफलतापूर्वक पंजीकृत हुई",
    "bookingSuccessSub": "डेटा राष्ट्रीय मंडी डेटाबेस के साथ सिंक हो गया।",
    "needTransport": "क्या इस उपज के लिए परिवहन सहायता चाहिए?",
    "cropName": "फसल का नाम",
    "estimatedQuantity": "अनुमानित मात्रा (क्विंटल)",
    "openStatus": "खुला है",
    "heavyRushStatus": "भारी भीड़",
    "closedStatus": "बंद है",
    "verifiedFarmerBadge": "सत्यापित किसान",
    "pendingVerifBadge": "सत्यापन लंबित",
    "mandiDashboardTitle": "मंडी संचालन डैशबोर्ड",
    "mandiDashboardSub": "किसानों के आगमन, सत्यापन और खरीद कतार का प्रबंधन करें।",
    "regManualArrival": "मैन्युअल आगमन दर्ज करें",
    "totalScheduled": "कुल निर्धारित",
    "waitingNext": "प्रतीक्षारत / अगला",
    "processedToday": "आज संसाधित",
    "verifPending": "सत्यापन लंबित",
    "upcomingQueue": "आगामी और प्रतीक्षा कतार",
    "completedEntries": "पूर्ण प्रविष्टियाँ",
    "timeSlot": "समय स्लॉट",
    "farmerAndToken": "किसान और टोकन",
    "action": "कार्यवाही",
    "markArrived": "आगमन दर्ज करें",
    "tokenNo": "टोकन नं.",
    "cropQty": "फसल (मात्रा)",
    "status": "स्थिति",
    "clearedGate": "गेट क्लियर",
    "farmerVerifReqs": "किसान सत्यापन अनुरोध",
    "approve": "स्वीकृत करें",
    "reject": "अस्वीकार करें",
    "todayMandiActivity": "आज की मंडी गतिविधि",
    "activity": "गतिविधि",
    "farmerVerifLabel": "किसान सत्यापन",
    "gateEntryLabel": "गेट प्रवेश",
    "procurementLabel": "खरीद",
    "manualArrivalTitle": "मैन्युअल आगमन दर्ज करें",
    "farmerMobile": "मोबाइल नंबर",
    "registerArrivalBtn": "आगमन पंजीकृत करें",
    "transportDashboardTitle": "परिवहन संचालन डैशबोर्ड",
    "transportDashboardSub": "किसान परिवहन अनुरोध, वाहन और सक्रिय यात्राओं का प्रबंधन करें।",
    "newRequests": "नए अनुरोध",
    "activeTrips": "सक्रिय यात्राएं",
    "completedTrips": "पूर्ण यात्राएं",
    "todayEarnings": "आज की कमाई",
    "newTransportRequests": "नए परिवहन अनुरोध",
    "myVehicles": "मेरे वाहन",
    "recentCompletedTrips": "हाल की पूर्ण यात्राएं",
    "farmerLabel": "किसान",
    "pickupLabel": "पिकअप स्थान",
    "destinationLabel": "गंतव्य",
    "vehicleLabel": "वाहन",
    "viewVerification": "सत्यापन देखें",
    "accept": "स्वीकार करें",
    "available": "उपलब्ध",
    "startTrip": "यात्रा शुरू करें",
    "reachedMandi": "मंडी पहुंचे",
    "completeTrip": "यात्रा पूर्ण करें",
    "selectVehicleModalTitle": "वाहन चुनें",
    "chooseVehicleSub": "इस परिवहन अनुरोध के लिए वाहन चुनें",
    "confirmBooking": "बुकिंग की पुष्टि करें",
    "farmerTrustVerifTitle": "किसान सत्यापन",
    "agrilinkTrustSub": "एग्रीलिंक सेवा विश्वास सत्यापन",
    "farmDetails": "खेत विवरण",
    "trustStatusHigh": "विश्वास स्थिति: उच्च",
    "trustDesc": "यह बुकिंग अनुरोध एक सत्यापित किसान द्वारा है।",
    "closeVerification": "सत्यापन विवरण बंद करें",
    "truck": "ट्रक",
    "tractor": "ट्रैक्टर / ट्रॉली",
    "mini": "छोटा वाहन",
    "goodsTransport": "सामान परिवहन",
    "reqAcceptedSuccess": "परिवहन अनुरोध सफलतापूर्वक स्वीकार किया गया!",
    "reqRejected": "अनुरोध अस्वीकार किया गया।",
    "tripStartedSuccess": "यात्रा सफलतापूर्वक शुरू हुई!",
    "tripReachedSuccess": "वाहन खरीद केंद्र पहुंच गया!",
    "tripCompletedSuccess": "यात्रा सफलतापूर्वक संपन्न हुई!",
    "bookingCreatedSuccess": "बुकिंग सफलतापूर्वक बनाई गई!",
    "profileNotFound": "प्रोफ़ाइल डेटा नहीं मिला! कृपया पंजीकरण करें।",
    "unauthorizedAccess": "अनधिकृत पहुंच।"
  },
  "gu": {
    "brand": "એગ્રીલિંક સેવા",
    "brandSub": "રાષ્ટ્રીય ડિજિટલ કૃષિ ખરીદી અને લોજિસ્ટિક્સ નેટવર્ક",
    "govIndia": "ભારત સરકાર",
    "govDept": "ગ્રાહક બાબતો, ખાદ્ય અને જાહેર વિતરણ મંત્રાલય",
    "nicCredit": "નેશનલ ઇન્ફોર્મેટિક્સ સેન્ટર (NIC) દ્વારા ડિઝાઇન અને હોસ્ટ કરેલ",
    "logout": "લૉગ આઉટ",
    "login": "લૉગ ઇન",
    "register": "નોંધણી",
    "secureLogin": "સુરક્ષિત લૉગિન",
    "authorizedLogin": "અધિકૃત લૉગિન",
    "citizenReg": "નાગરિક નોંધણી",
    "welcome": "સ્વાગત છે",
    "live": "લાઇવ",
    "roleFarmer": "ખેડૂત (Farmer)",
    "roleTransporter": "પરિવહન ભાગીદાર (Transporter)",
    "roleOperator": "મંડી ઓપરેટર (Operator)",
    "farmerPortal": "રાષ્ટ્રીય ખેડૂત પોર્ટલ",
    "transporterPortal": "ટ્રાન્સપોર્ટર મેનેજમેન્ટ સિસ્ટમ",
    "operatorPortal": "મંડી ઓપરેટર પોર્ટલ",
    "operatorSub": "ગેટ અને કતાર વ્યવસ્થાપન સિસ્ટમ",
    "farmerDashboardTitle": "ખરીદી ડેશબોર્ડ",
    "farmerDashboardSub": "તમારો પાક જમા કરવાનો સમય નક્કી કરો અને ડિજિટલ ગેટ પાસ સંચાલિત કરો.",
    "activeRegion": "સક્રિય વિસ્તાર",
    "nearbyCenters": "નજીકના ખરીદ કેન્દ્રો",
    "bookingLockedMsg": "પાક પહોંચાડવા સુધી ડેશબોર્ડ લૉક છે",
    "validPass": "માન્ય પાસ",
    "destinationMandi": "ગંતવ્ય મંડી",
    "mandiName": "મંડીનું નામ",
    "tokenId": "ટોકન નંબર",
    "farmerName": "ખેડૂતનું નામ",
    "reportingDate": "રિપોર્ટિંગ તારીખ",
    "assignedTimeSlot": "ફાળવેલ સમય સ્લોટ",
    "scanAtBridge": "તોલકાંટા પર સ્કેન કરો",
    "printPass": "પાસ પ્રિન્ટ કરો",
    "printTicket": "ટિકિટ પ્રિન્ટ કરો",
    "returnDashboard": "ડેશબોર્ડ પર પાછા જાઓ",
    "bookingSlotFor": "સ્લોટ બુકિંગ કેન્દ્ર",
    "continuousSlotsSub": "15-મિનિટ અંતરાલ",
    "reviewConfirm": "વિનંતીની સમીક્ષા અને પુષ્ટિ",
    "citizenDetailsVerif": "નાગરિક વિગતોની ચકાસણી",
    "registeredPin": "નોંધાયેલ પિન કોડ",
    "arrivalTimeSlot": "આગમન સમય સ્લોટ",
    "confirmSyncBtn": "પુષ્ટિ કરો અને ડેટાબેઝ સાથે સિંક કરો",
    "bookingSuccessTitle": "બુકિંગ સફળતાપૂર્વક નોંધાયું",
    "bookingSuccessSub": "તમારો ડેટા રાષ્ટ્રીય મંડી ડેટાબેઝ સાથે સિંક થયો.",
    "needTransport": "શું આ પાક માટે પરિવહનની જરૂર છે?",
    "cropName": "પાકનું નામ",
    "estimatedQuantity": "અંદાજિત જથ્થો (ક્વિન્ટલ)",
    "openStatus": "ખુલ્લું છે",
    "heavyRushStatus": "ભારે ભીડ",
    "closedStatus": "બંધ છે",
    "verifiedFarmerBadge": "ચકાસાયેલ ખેડૂત",
    "pendingVerifBadge": "ચકાસણી બાકી",
    "mandiDashboardTitle": "મંડી ઓપરેશન્સ ડેશબોર્ડ",
    "mandiDashboardSub": "ખેડૂત આગમન, ચકાસણી અને ખરીદી કતારનું સંચાલન કરો.",
    "regManualArrival": "મેન્યુઅલ આગમન નોંધાવો",
    "totalScheduled": "કુલ નિર્ધારિત",
    "waitingNext": "પ્રતીક્ષામાં / આગામી",
    "processedToday": "આજે પ્રક્રિયા કરેલ",
    "verifPending": "ચકાસણી બાકી",
    "upcomingQueue": "આગામી અને પ્રતીક્ષા કતાર",
    "completedEntries": "પૂર્ણ થયેલ એન્ટ્રીઓ",
    "timeSlot": "સમય સ્લોટ",
    "farmerAndToken": "ખેડૂત અને ટોકન",
    "action": "કાર્યવાહી",
    "markArrived": "આગમન નોંધાવો",
    "tokenNo": "ટોકન નં.",
    "cropQty": "પાક (જથ્થો)",
    "status": "સ્થિતિ",
    "clearedGate": "ગેટ ક્લિયર",
    "farmerVerifReqs": "ખેડૂત ચકાસણી વિનંતીઓ",
    "approve": "મંજૂર કરો",
    "reject": "નકારો",
    "todayMandiActivity": "આજની મંડી પ્રવૃત્તિ",
    "activity": "પ્રવૃત્તિ",
    "farmerVerifLabel": "ખેડૂત ચકાસણી",
    "gateEntryLabel": "ગેટ પ્રવેશ",
    "procurementLabel": "ખરીદી",
    "manualArrivalTitle": "મેન્યુઅલ આગમન નોંધાવો",
    "farmerMobile": "મોબાઇલ નંબર",
    "registerArrivalBtn": "આગમન નોંધાવો",
    "transportDashboardTitle": "પરિવહન ઓપરેશન્સ ડેશબોર્ડ",
    "transportDashboardSub": "ખેડૂત પરિવહન વિનંતીઓ, વાહનો અને સક્રિય મુસાફરીનું સંચાલન કરો.",
    "newRequests": "નવી વિનંતીઓ",
    "activeTrips": "સક્રિય મુસાફરી",
    "completedTrips": "પૂર્ણ મુસાફરી",
    "todayEarnings": "આજની કમાણી",
    "newTransportRequests": "નવી પરિવહન વિનંતીઓ",
    "myVehicles": "મારા વાહનો",
    "recentCompletedTrips": "તાજેતરની પૂર્ણ મુસાફરી",
    "farmerLabel": "ખેડૂત",
    "pickupLabel": "પિકઅપ સ્થળ",
    "destinationLabel": "ગંતવ્ય",
    "vehicleLabel": "વાહન",
    "viewVerification": "ચકાસણી જુઓ",
    "accept": "સ્વીકારો",
    "available": "ઉપલબ્ધ",
    "startTrip": "મુસાફરી શરૂ કરો",
    "reachedMandi": "મંડી પહોંચ્યા",
    "completeTrip": "મુસાફરી પૂર્ણ કરો",
    "selectVehicleModalTitle": "વાહન પસંદ કરો",
    "chooseVehicleSub": "આ પરિવહન વિનંતી માટે વાહન પસંદ કરો",
    "confirmBooking": "બુકિંગની પુષ્ટિ કરો",
    "farmerTrustVerifTitle": "ખેડૂત ચકાસણી",
    "agrilinkTrustSub": "એગ્રીલિંક સેવા વિશ્વાસ ચકાસણી",
    "farmDetails": "ખેતર વિગતો",
    "trustStatusHigh": "વિશ્વાસ સ્થિતિ: ઉચ્ચ",
    "trustDesc": "આ બુકિંગ વિનંતી ચકાસાયેલ ખેડૂત તરફથી છે.",
    "closeVerification": "ચકાસણી વિગતો બંધ કરો",
    "truck": "ટ્રક",
    "tractor": "ટ્રેક્ટર / ટ્રોલી",
    "mini": "નાનું વાહન",
    "goodsTransport": "માલ પરિવહન",
    "reqAcceptedSuccess": "પરિવહન વિનંતી સફળતાપૂર્વક સ્વીકારાઈ!",
    "reqRejected": "વિનંતી નકારી કાઢવામાં આવી.",
    "tripStartedSuccess": "મુસાફરી શરૂ થઈ!",
    "tripReachedSuccess": "વાહન ખરીદ કેન્દ્ર પર પહોંચી ગયું!",
    "tripCompletedSuccess": "મુસાફરી સફળતાપૂર્વક પૂર્ણ થઈ!",
    "bookingCreatedSuccess": "બુકિંગ સફળતાપૂર્વક બનાવવામાં આવ્યું!",
    "profileNotFound": "પ્રોફાઇલ ડેટા મળ્યો નથી!",
    "unauthorizedAccess": "અનધિકૃત પ્રવેશ."
  },
  "mr": {
    "brand": "ॲग्रीलिंक सेवा",
    "brandSub": "राष्ट्रीय डिजिटल कृषी खरेदी आणि वाहतूक समन्वय प्रणाली",
    "govIndia": "भारत सरकार",
    "govDept": "ग्राहक व्यवहार, अन्न आणि सार्वजनिक वितरण मंत्रालय",
    "nicCredit": "राष्ट्रीय सूचना विज्ञान केंद्र (NIC) द्वारे डिझाइन आणि होस्ट केलेले",
    "logout": "लॉग आउट",
    "login": "लॉग इन",
    "register": "नोंदणी",
    "secureLogin": "सुरक्षित लॉगिन",
    "authorizedLogin": "अधिकृत लॉगिन",
    "citizenReg": "नागरिक नोंदणी",
    "welcome": "स्वागत आहे",
    "live": "लाइव्ह",
    "roleFarmer": "शेतकरी (Farmer)",
    "roleTransporter": "वाहतूकदार (Transporter)",
    "roleOperator": "मंडी अधिकारी (Operator)",
    "farmerPortal": "राष्ट्रीय शेतकरी पोर्टल",
    "transporterPortal": "वाहतूक व्यवस्थापन प्रणाली",
    "operatorPortal": "मंडी ऑपरेटर पोर्टल",
    "operatorSub": "गेट आणि रांग व्यवस्थापन प्रणाली",
    "farmerDashboardTitle": "खरेदी डॅशबोर्ड",
    "farmerDashboardSub": "आपले पीक जमा करण्याची वेळ निश्चित करा आणि डिजिटल गेट पास व्यवस्थापित करा.",
    "activeRegion": "सक्रिय क्षेत्र",
    "nearbyCenters": "जवळचे खरेदी केंद्र",
    "bookingLockedMsg": "पीक जमा होईपर्यंत डॅशबोर्ड लॉक आहे",
    "validPass": "वैध पास",
    "destinationMandi": "गंतव्य मंडी",
    "mandiName": "मंडीचे नाव",
    "tokenId": "टोकन क्रमांक",
    "farmerName": "शेतकऱ्याचे नाव",
    "reportingDate": "तारीख",
    "assignedTimeSlot": "नेमून दिलेली वेळ",
    "scanAtBridge": "वजन काट्यावर स्कॅन करा",
    "printPass": "पास प्रिंट करा",
    "printTicket": "तिकीट प्रिंट करा",
    "returnDashboard": "डॅशबोर्डवर परत जा",
    "bookingSlotFor": "स्लॉट बुकिंग केंद्र",
    "continuousSlotsSub": "15-मिनिट अंतर",
    "reviewConfirm": "पुनरावलोकन आणि पुष्टी करा",
    "citizenDetailsVerif": "नागरिक तपशील पडताळणी",
    "registeredPin": "नोंदणीकृत पिन कोड",
    "arrivalTimeSlot": "आगमन वेळ स्लॉट",
    "confirmSyncBtn": "पुष्टी करा आणि डेटाबेसमध्ये सिंक करा",
    "bookingSuccessTitle": "बुकिंग यशस्वीरित्या नोंदवली गेली",
    "bookingSuccessSub": "आपला डेटा राष्ट्रीय मंडी डेटाबेससह सिंक झाला.",
    "needTransport": "या पिकासाठी वाहतूक सहाय्य हवे आहे का?",
    "cropName": "पिकाचे नाव",
    "estimatedQuantity": "अंदाजे प्रमाण (क्विंटल)",
    "openStatus": "सुरू आहे",
    "heavyRushStatus": "जास्त गर्दी",
    "closedStatus": "बंद आहे",
    "verifiedFarmerBadge": "पडताळणी झालेला शेतकरी",
    "pendingVerifBadge": "पडताळणी प्रलंबित",
    "mandiDashboardTitle": "मंडी ऑपरेशन्स डॅशबोर्ड",
    "mandiDashboardSub": "शेतकरी आगमन, पडताळणी, टोकन आणि खरेदी रांगेचे व्यवस्थापन करा.",
    "regManualArrival": "मॅन्युअल आगमन नोंदवा",
    "totalScheduled": "एकूण नियोजित",
    "waitingNext": "प्रतीक्षा / पुढील",
    "processedToday": "आज प्रक्रिया केलेले",
    "verifPending": "पडताळणी प्रलंबित",
    "upcomingQueue": "आगामी आणि प्रतीक्षा रांग",
    "completedEntries": "पूर्ण नोंदी",
    "timeSlot": "वेळ",
    "farmerAndToken": "शेतकरी आणि टोकन",
    "action": "कृती",
    "markArrived": "आगमन नोंदवा",
    "tokenNo": "टोकन क्र.",
    "cropQty": "पीक (प्रमाण)",
    "status": "स्थिती",
    "clearedGate": "गेट क्लिअर",
    "farmerVerifReqs": "शेतकरी पडताळणी विनंत्या",
    "approve": "मंजूर करा",
    "reject": "नाकारा",
    "todayMandiActivity": "आजची मंडी गतिविधी",
    "activity": "गतिविधी",
    "farmerVerifLabel": "शेतकरी पडताळणी",
    "gateEntryLabel": "गेट प्रवेश",
    "procurementLabel": "खरेदी",
    "manualArrivalTitle": "मॅन्युअल आगमन नोंदवा",
    "farmerMobile": "मोबाइल नंबर",
    "registerArrivalBtn": "आगमन नोंदवा",
    "transportDashboardTitle": "वाहतूक संचालन डॅशबोर्ड",
    "transportDashboardSub": "शेतकरी वाहतूक विनंत्या, वाहने आणि सक्रिय प्रवास व्यवस्थापित करा.",
    "newRequests": "नवीन विनंत्या",
    "activeTrips": "सक्रिय प्रवास",
    "completedTrips": "पूर्ण प्रवास",
    "todayEarnings": "आजची कमाई",
    "newTransportRequests": "नवीन वाहतूक विनंत्या",
    "myVehicles": "माझी वाहने",
    "recentCompletedTrips": "अलीकडील पूर्ण प्रवास",
    "farmerLabel": "शेतकरी",
    "pickupLabel": "पिकअप ठिकाण",
    "destinationLabel": "गंतव्य",
    "vehicleLabel": "वाहन",
    "viewVerification": "पडताळणी पहा",
    "accept": "स्वीकारा",
    "available": "उपलब्ध",
    "startTrip": "प्रवास सुरू करा",
    "reachedMandi": "मंडीत पोहोचलो",
    "completeTrip": "प्रवास पूर्ण करा",
    "selectVehicleModalTitle": "वाहन निवडा",
    "chooseVehicleSub": "या वाहतूक विनंतीसाठी वाहन निवडा",
    "confirmBooking": "बुकिंगची पुष्टी करा",
    "farmerTrustVerifTitle": "शेतकरी पडताळणी",
    "agrilinkTrustSub": "ॲग्रीलिंक सेवा विश्वास पडताळणी",
    "farmDetails": "शेताची माहिती",
    "trustStatusHigh": "विश्वास स्थिती: उच्च",
    "trustDesc": "ही बुकिंग विनंती पडताळणी केलेल्या शेतकऱ्याकडून आहे.",
    "closeVerification": "पडताळणी तपशील बंद करा",
    "truck": "ट्रक",
    "tractor": "ट्रॅक्टर / ट्रॉली",
    "mini": "लहान वाहन",
    "goodsTransport": "माल वाहतूक",
    "reqAcceptedSuccess": "वाहतूक विनंती यशस्वीरित्या स्वीकारली गेली!",
    "reqRejected": "विनंती नाकारली गेली.",
    "tripStartedSuccess": "प्रवास सुरू झाला!",
    "tripReachedSuccess": "वाहन खरेदी केंद्रात पोहोचले!",
    "tripCompletedSuccess": "प्रवास यशस्वीरित्या पूर्ण झाला!",
    "bookingCreatedSuccess": "बुकिंग यशस्वीरित्या तयार झाली!",
    "profileNotFound": "प्रोफाइल सापडली नाही!",
    "unauthorizedAccess": "अनधिकृत प्रवेश."
  },
  "bn": {
    "brand": "এগ্রিলিংক সেবা",
    "brandSub": "জাতীয় ডিজিটাল কৃষি সংগ্রহ ও লজিস্টিকস নেটওয়ার্ক",
    "govIndia": "ভারত সরকার",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "লগআউট",
    "login": "লগইন",
    "register": "নিবন্ধন",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "স্বাগতম",
    "live": "লাইভ",
    "roleFarmer": "কৃষক (Farmer)",
    "roleTransporter": "পরিবহন অংশীদার",
    "roleOperator": "মান্ডি কর্মকর্তা",
    "farmerPortal": "জাতীয় কৃষক পোর্টাল",
    "transporterPortal": "পরিবহন ব্যবস্থাপনা সিস্টেম",
    "operatorPortal": "মান্ডি অপারেটর পোর্টাল",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "মান্ডির নাম",
    "mandiName": "মান্ডির নাম",
    "tokenId": "টোকেন নং",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "ওয়েব্রিজে স্ক্যান করুন",
    "printPass": "টিকিট প্রিন্ট করুন",
    "printTicket": "টিকিট প্রিন্ট করুন",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "পরিবহন সহায়তা প্রয়োজন?",
    "cropName": "ফসলের নাম",
    "estimatedQuantity": "পরিমাণ (কুইন্টাল)",
    "openStatus": "খোলা",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "যাচাইকৃত কৃষক",
    "pendingVerifBadge": "যাচাইকরণ বাকি",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "টোকেন নং",
    "cropQty": "Crop (Qty)",
    "status": "অবস্থা",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "অনুমোদন",
    "reject": "প্রত্যাখ্যান",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "যাত্রা শুরু করুন",
    "reachedMandi": "মান্ডিতে পৌঁছেছে",
    "completeTrip": "যাত্রা সম্পন্ন করুন",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "ta": {
    "brand": "அக்ரிலிங்க் சேவா",
    "brandSub": "தேசிய டிஜிட்டல் விவசாய கொள்முதல் நெட்வொர்க்",
    "govIndia": "இந்திய அரசு",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "வெளியேறு",
    "login": "உள்நுழை",
    "register": "பதிவு செய்",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "வரவேற்கிறோம்",
    "live": "நேரலை",
    "roleFarmer": "விவசாயி (Farmer)",
    "roleTransporter": "போக்குவரத்து பங்குதாரர்",
    "roleOperator": "மண்டி அதிகாரி",
    "farmerPortal": "தேசிய உழவர் தளம்",
    "transporterPortal": "போக்குவரத்து மேலாண்மை அமைப்பு",
    "operatorPortal": "மண்டி ஆபரேட்டர் தளம்",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "மண்டி பெயர்",
    "mandiName": "மண்டி பெயர்",
    "tokenId": "டோக்கன் எண்",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "எடை மேடையில் ஸ்கேன் செய்யவும்",
    "printPass": "டிக்கெட் அச்சிடுக",
    "printTicket": "டிக்கெட் அச்சிடுக",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "போக்குவரத்து உதவி தேவையா?",
    "cropName": "பயிர் பெயர்",
    "estimatedQuantity": "அளவு (குவிண்டால்)",
    "openStatus": "திறந்துள்ளது",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "சரிபார்க்கப்பட்ட விவசாயி",
    "pendingVerifBadge": "சரிபார்ப்பு நிலுவையில்",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "டோக்கன் எண்",
    "cropQty": "Crop (Qty)",
    "status": "நிலை",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "ஏற்கவும்",
    "reject": "நிராகரி",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "பயணத்தை தொடங்கு",
    "reachedMandi": "மண்டியை அடைந்தது",
    "completeTrip": "பயணத்தை முடி",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "te": {
    "brand": "అగ్రిలింక్ సేవ",
    "brandSub": "జాతీయ డిజిటల్ వ్యవసాయ సేకరణ నెట్‌వర్క్",
    "govIndia": "భారత ప్రభుత్వం",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "లాగౌట్",
    "login": "లాగిన్",
    "register": "నమోదు",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "స్వాగతం",
    "live": "లైవ్",
    "roleFarmer": "రైతు (Farmer)",
    "roleTransporter": "రవాణా భాగస్వామి",
    "roleOperator": "మండి అధికారి",
    "farmerPortal": "జాతీయ రైతు పోర్టల్",
    "transporterPortal": "రవాణా నిర్వహణ వ్యవస్థ",
    "operatorPortal": "మండి ఆపరేటర్ పోర్టల్",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "మండి పేరు",
    "mandiName": "మండి పేరు",
    "tokenId": "టోకెన్ నంబర్",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "వేబ్రిడ్జ్ వద్ద స్కాన్ చేయండి",
    "printPass": "టికెట్ ప్రింట్ చేయండి",
    "printTicket": "టికెట్ ప్రింట్ చేయండి",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "రవాణా సహాయం కావాలా?",
    "cropName": "పంట పేరు",
    "estimatedQuantity": "పరిమాణం (క్వింటాళ్ళు)",
    "openStatus": "తెరిచి ఉంది",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "ధృవీకరించబడిన రైతు",
    "pendingVerifBadge": "ధృవీకరణ పెండింగ్‌లో ఉంది",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "టోకెన్ నంబర్",
    "cropQty": "Crop (Qty)",
    "status": "స్థితి",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "ఆమోదించండి",
    "reject": "తిరస్కరించండి",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "ప్రయాణాన్ని ప్రారంభించండి",
    "reachedMandi": "మండి చేరుకుంది",
    "completeTrip": "ప్రయాణాన్ని పూర్తి చేయండి",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "kn": {
    "brand": "ಅಗ್ರಿಲಿಂಕ್ ಸೇವೆ",
    "brandSub": "ರಾಷ್ಟ್ರೀಯ ಡಿಜಿಟಲ್ ಕೃಷಿ ಸಂಗ್ರಹಣೆ ನೆಟ್‌ವರ್ಕ್",
    "govIndia": "ಭಾರತ ಸರ್ಕಾರ",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "ಲಾಗ್‌ಔಟ್",
    "login": "ಲಾಗಿನ್",
    "register": "ನೋಂದಣಿ",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "ಸ್ವಾಗತ",
    "live": "ಲೈವ್",
    "roleFarmer": "ರೈತ (Farmer)",
    "roleTransporter": "ಸಾರಿಗೆ ಪಾಲುದಾರ",
    "roleOperator": "ಮಂಡಿ ಅಧಿಕಾರಿ",
    "farmerPortal": "ರಾಷ್ಟ್ರೀಯ ರೈತ ಪೋರ್ಟಲ್",
    "transporterPortal": "ಸಾರಿಗೆ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ",
    "operatorPortal": "ಮಂಡಿ ಆಪರೇಟರ್ ಪೋರ್ಟಲ್",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "ಮಂಡಿ ಹೆಸರು",
    "mandiName": "ಮಂಡಿ ಹೆಸರು",
    "tokenId": "ಟೋಕನ್ ಸಂಖ್ಯೆ",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "ತೂಕದ ಸೇತುವೆಯಲ್ಲಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    "printPass": "ಟಿಕೆಟ್ ಮುದ್ರಿಸಿ",
    "printTicket": "ಟಿಕೆಟ್ ಮುದ್ರಿಸಿ",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "ಸಾರಿಗೆ ಬೆಂಬಲ ಬೇಕೇ?",
    "cropName": "ಬೆಳೆ ಹೆಸರು",
    "estimatedQuantity": "ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)",
    "openStatus": "ತೆರೆದಿದೆ",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "ಪರಿಶೀಲಿಸಿದ ರೈತ",
    "pendingVerifBadge": "ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "ಟೋಕನ್ ಸಂಖ್ಯೆ",
    "cropQty": "Crop (Qty)",
    "status": "ಸ್ಥಿತಿ",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "ಅನುಮೋದಿಸಿ",
    "reject": "ತಿರಸ್ಕರಿಸಿ",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "ಪ್ರವಾಸ ಪ್ರಾರಂಭಿಸಿ",
    "reachedMandi": "ಮಂಡಿ ತಲುಪಿದೆ",
    "completeTrip": "ಪ್ರವಾಸ ಪೂರ್ಣಗೊಳಿಸಿ",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "ml": {
    "brand": "അഗ്രിലിങ്ക് സേവ",
    "brandSub": "ദേശീയ ഡിജിറ്റൽ കാർഷിക സംഭരണ ​​നെറ്റ്‌വർക്ക്",
    "govIndia": "ഭാരത സർക്കാർ",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "ലോഗൗട്ട്",
    "login": "ലോഗിൻ",
    "register": "രജിസ്റ്റർ",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "സ്വാഗതം",
    "live": "തത്സമയം",
    "roleFarmer": "കർഷകൻ (Farmer)",
    "roleTransporter": "ഗതാഗത പങ്കാളി",
    "roleOperator": "മണ്ടി ഉദ്യോഗസ്ഥൻ",
    "farmerPortal": "ദേശീയ കർഷക പോർട്ടൽ",
    "transporterPortal": "ഗതാഗത മാനേജ്മെന്റ് സിസ്റ്റം",
    "operatorPortal": "മണ്ടി ഓപ്പറേറ്റർ പോർട്ടൽ",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "മണ്ടിയുടെ പേര്",
    "mandiName": "മണ്ടിയുടെ പേര്",
    "tokenId": "ടോക്കൺ നമ്പർ",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "വെയ്‌ബ്രിഡ്ജിൽ സ്കാൻ ചെയ്യുക",
    "printPass": "ടിക്കറ്റ് പ്രിന്റ് ചെയ്യുക",
    "printTicket": "ടിക്കറ്റ് പ്രിന്റ് ചെയ്യുക",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "ഗതാഗത സഹായം ആവശ്യമുണ്ടോ?",
    "cropName": "വിളയുടെ പേര്",
    "estimatedQuantity": "അളവ് (ക്വിന്റൽ)",
    "openStatus": "തുറന്നിരിക്കുന്നു",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "സ്ഥിരീകരിച്ച കർഷകൻ",
    "pendingVerifBadge": "പരിശോധന ബാക്കിയുണ്ട്",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "ടോക്കൺ നമ്പർ",
    "cropQty": "Crop (Qty)",
    "status": "നില",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "അംഗീകരിക്കുക",
    "reject": "നിരസിക്കുക",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "യാത്ര ആരംഭിക്കുക",
    "reachedMandi": "മണ്ടിയിലെത്തി",
    "completeTrip": "യാത്ര പൂർത്തിയാക്കുക",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "pa": {
    "brand": "ਐਗਰੀਲਿੰਕ ਸੇਵਾ",
    "brandSub": "ਰਾਸ਼ਟਰੀ ਡਿਜੀਟਲ ਖੇਤੀਬਾੜੀ ਖਰੀਦ ਨੈੱਟਵਰਕ",
    "govIndia": "ਭਾਰਤ ਸਰਕਾਰ",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "ਲਾਗ ਆਉਟ",
    "login": "ਲਾਗ ਇਨ",
    "register": "ਰਜਿਸਟਰ",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "ਜੀ ਆਇਆਂ ਨੂੰ",
    "live": "ਲਾਈਵ",
    "roleFarmer": "ਕਿਸਾਨ (Farmer)",
    "roleTransporter": "ਟਰਾਂਸਪੋਰਟ ਪਾਰਟਨਰ",
    "roleOperator": "ਮੰਡੀ ਅਧਿਕਾਰੀ",
    "farmerPortal": "ਰਾਸ਼ਟਰੀ ਕਿਸਾਨ ਪੋਰਟਲ",
    "transporterPortal": "ਟਰਾਂਸਪੋਰਟ ਪ੍ਰਬੰਧਨ ਸਿਸਟਮ",
    "operatorPortal": "ਮੰਡੀ ਆਪਰੇਟਰ ਪੋਰਟਲ",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "ਮੰਡੀ ਦਾ ਨਾਮ",
    "mandiName": "ਮੰਡੀ ਦਾ ਨਾਮ",
    "tokenId": "ਟੋਕਨ ਨੰਬਰ",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "ਕੰਡੇ 'ਤੇ ਸਕੈਨ ਕਰੋ",
    "printPass": "ਟਿਕਟ ਪ੍ਰਿੰਟ ਕਰੋ",
    "printTicket": "ਟਿਕਟ ਪ੍ਰਿੰਟ ਕਰੋ",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "ਆਵਾਜਾਈ ਦੀ ਲੋੜ ਹੈ?",
    "cropName": "ਫਸਲ ਦਾ ਨਾਮ",
    "estimatedQuantity": "ਮਾਤਰਾ (ਕੁਇੰਟਲ)",
    "openStatus": "ਖੁੱਲ੍ਹਾ ਹੈ",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "ਪ੍ਰਮਾਣਿਤ ਕਿਸਾਨ",
    "pendingVerifBadge": "ਪੜਤਾਲ ਬਾਕੀ ਹੈ",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "ਟੋਕਨ ਨੰਬਰ",
    "cropQty": "Crop (Qty)",
    "status": "ਸਥਿਤੀ",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "ਮਨਜ਼ੂਰ",
    "reject": "ਰੱਦ ਕਰੋ",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ",
    "reachedMandi": "ਮੰਡੀ ਪਹੁੰਚ ਗਏ",
    "completeTrip": "ਯਾਤਰਾ ਪੂਰੀ ਕਰੋ",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "or": {
    "brand": "ଏଗ୍ରିଲିଙ୍କ ସେବା",
    "brandSub": "ଜାତୀୟ ଡିଜିଟାଲ କୃଷି କ୍ରୟ ନେଟୱାର୍କ",
    "govIndia": "ଭାରତ ସରକାର",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "ଲଗ୍ ଆଉଟ୍",
    "login": "ଲଗ୍ ଇନ୍",
    "register": "ପଞ୍ଜୀକରଣ",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "ସ୍ୱାଗତ",
    "live": "ଲାଇଭ୍",
    "roleFarmer": "କୃଷକ (Farmer)",
    "roleTransporter": "ପରିବହନ ସହଯୋଗୀ",
    "roleOperator": "ମଣ୍ଡି ଅଧିକାରୀ",
    "farmerPortal": "ଜାତୀୟ କୃଷକ ପୋର୍ଟାଲ୍",
    "transporterPortal": "ପରିବହନ ପରିଚାଳନା ପ୍ରଣାଳୀ",
    "operatorPortal": "ମଣ୍ଡି ଅପରେଟର ପୋର୍ଟାଲ୍",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "ମଣ୍ଡି ନାମ",
    "mandiName": "ମଣ୍ଡି ନାମ",
    "tokenId": "ଟୋକନ୍ ନଂ",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "ଓଜନ ପୋଲରେ ସ୍କାନ୍ କରନ୍ତୁ",
    "printPass": "ଟିକେଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ",
    "printTicket": "ଟିକେଟ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "ପରିବହନ ସହାୟତା ଆବଶ୍ୟକ କି?",
    "cropName": "ଫସଲର ନାମ",
    "estimatedQuantity": "ପରିମାଣ (କ୍ୱିଣ୍ଟାଲ)",
    "openStatus": "ଖୋଲା ଅଛି",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "ପ୍ରମାଣିତ କୃଷକ",
    "pendingVerifBadge": "ଯାଞ୍ଚ ବାକି ଅଛି",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "ଟୋକନ୍ ନଂ",
    "cropQty": "Crop (Qty)",
    "status": "ସ୍ଥିତି",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "ଅନୁମୋଦନ",
    "reject": "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "ଯାତ୍ରା ଆରମ୍ଭ କରନ୍ତୁ",
    "reachedMandi": "ମଣ୍ଡିରେ ପହଞ୍ଚିଲା",
    "completeTrip": "ଯାତ୍ରା ସମାପ୍ତ କରନ୍ତୁ",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "as": {
    "brand": "এগ্ৰিলিংক সেৱা",
    "brandSub": "ৰাষ্ট্ৰীয় ডিজিটেল কৃষি ক্ৰয় নেটৱৰ্ক",
    "govIndia": "ভাৰত চৰকাৰ",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "লগ আউট",
    "login": "লগ ইন",
    "register": "পঞ্জীয়ন",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "স্বাগতম",
    "live": "লাইভ",
    "roleFarmer": "কৃষক (Farmer)",
    "roleTransporter": "পৰিবহণ অংশীদাৰ",
    "roleOperator": "মাণ্ডি বিষয়া",
    "farmerPortal": "ৰাষ্ট্ৰীয় কৃষক প'ৰ্টেল",
    "transporterPortal": "পৰিবহণ ব্যৱস্থাপনা ব্যৱস্থা",
    "operatorPortal": "মাণ্ডি অপাৰেটৰ প'ৰ্টেল",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "মাণ্ডিৰ নাম",
    "mandiName": "মাণ্ডিৰ নাম",
    "tokenId": "টোকেন নং",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "ওজন দলঙত স্কেন কৰক",
    "printPass": "টিকট প্ৰিণ্ট কৰক",
    "printTicket": "টিকট প্ৰিণ্ট কৰক",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "পৰিবহণৰ সহায় লাগিব নেকি?",
    "cropName": "শস্যৰ নাম",
    "estimatedQuantity": "পৰিমাণ (কুইন্টল)",
    "openStatus": "খোলা আছে",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "সত্যাপন কৰা কৃষক",
    "pendingVerifBadge": "সত্যাপন বাকী আছে",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "টোকেন নং",
    "cropQty": "Crop (Qty)",
    "status": "স্থিতি",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "অনুমোদন",
    "reject": "প্ৰত্যাখ্যান",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "যাত্ৰা আৰম্ভ কৰক",
    "reachedMandi": "মাণ্ডিত উপনীত হ'ল",
    "completeTrip": "যাত্ৰা সম্পূৰ্ণ কৰক",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  },
  "ur": {
    "brand": "ایگری لنک سیوا",
    "brandSub": "قومی ڈیجیٹل زرعی خریداری اور لاجسٹکس نیٹ ورک",
    "govIndia": "حکومت ہند",
    "govDept": "Ministry of Consumer Affairs, Food & Public Distribution",
    "nicCredit": "Designed, Developed and Hosted by National Informatics Centre (NIC)",
    "logout": "لاگ آؤٹ",
    "login": "لاگ ان",
    "register": "رجسٹریشن",
    "secureLogin": "Secure Login",
    "authorizedLogin": "Authorized Login",
    "citizenReg": "Citizen Registration",
    "welcome": "خوش آمدید",
    "live": "لائیو",
    "roleFarmer": "کسان (Farmer)",
    "roleTransporter": "لاجسٹکس پارٹنر (Transporter)",
    "roleOperator": "منڈی آپریٹر (Official)",
    "farmerPortal": "قومی کسان پورٹل",
    "transporterPortal": "ٹرانسپورٹر مینجمنٹ سسٹم",
    "operatorPortal": "منڈی آپریٹر پورٹل",
    "operatorSub": "GATE & QUEUE MANAGEMENT SYSTEM",
    "farmerDashboardTitle": "Procurement Dashboard",
    "farmerDashboardSub": "Schedule your crop drop-off and manage digital gate passes.",
    "activeRegion": "Active Region",
    "nearbyCenters": "Nearby Procurement Centers",
    "bookingLockedMsg": "Dashboard Locked until Drop-off",
    "validPass": "Valid Pass",
    "destinationMandi": "منڈی کا نام",
    "mandiName": "منڈی کا نام",
    "tokenId": "ٹوکن نمبر",
    "farmerName": "Farmer Name",
    "reportingDate": "Reporting Date",
    "assignedTimeSlot": "Assigned Time Slot",
    "scanAtBridge": "وی برج پر اسکین کریں",
    "printPass": "ٹکٹ پرنٹ کریں",
    "printTicket": "ٹکٹ پرنٹ کریں",
    "returnDashboard": "Return to Dashboard",
    "bookingSlotFor": "Booking Slot For",
    "continuousSlotsSub": "15-Minute Intervals",
    "reviewConfirm": "Review & Confirm Request",
    "citizenDetailsVerif": "Citizen Details Verification",
    "registeredPin": "Registered PIN Code",
    "arrivalTimeSlot": "Arrival Time Slot",
    "confirmSyncBtn": "Confirm & Sync with Database",
    "bookingSuccessTitle": "Booking Registered Successfully",
    "bookingSuccessSub": "Your data is synced with the National Mandi Database.",
    "needTransport": "کیا نقل و حمل کی مدد درکار ہے؟",
    "cropName": "فصل کا نام",
    "estimatedQuantity": "مقدار (کوئنٹل)",
    "openStatus": "کھلا ہے",
    "heavyRushStatus": "HEAVY RUSH",
    "closedStatus": "CLOSED",
    "verifiedFarmerBadge": "تصدیق شدہ کسان",
    "pendingVerifBadge": "تصدیق زیر التواء",
    "mandiDashboardTitle": "Mandi Operations Dashboard",
    "mandiDashboardSub": "Manage farmer arrivals, verification, tokens and procurement queue.",
    "regManualArrival": "Register Manual Arrival",
    "totalScheduled": "Total Scheduled",
    "waitingNext": "Waiting / Next Up",
    "processedToday": "Processed Today",
    "verifPending": "Verification Pending",
    "upcomingQueue": "Upcoming & Waiting Queue",
    "completedEntries": "Completed Entries",
    "timeSlot": "Time Slot",
    "farmerAndToken": "Farmer & Token",
    "action": "Action",
    "markArrived": "Mark Arrived",
    "tokenNo": "ٹوکن نمبر",
    "cropQty": "Crop (Qty)",
    "status": "حیثیت",
    "clearedGate": "CLEARED GATE",
    "farmerVerifReqs": "Farmer Verification Requests",
    "approve": "منظور کریں",
    "reject": "مسترد کریں",
    "todayMandiActivity": "Today's Mandi Activity",
    "activity": "Activity",
    "farmerVerifLabel": "Farmer Verification",
    "gateEntryLabel": "Gate Entry",
    "procurementLabel": "Procurement",
    "manualArrivalTitle": "Register Manual Arrival",
    "farmerMobile": "Mobile Number",
    "registerArrivalBtn": "Register Arrival",
    "transportDashboardTitle": "Transport Operations Dashboard",
    "transportDashboardSub": "Manage farmer transport requests, vehicles and active trips.",
    "newRequests": "New Requests",
    "activeTrips": "Active Trips",
    "completedTrips": "Completed Trips",
    "todayEarnings": "Today's Earnings",
    "newTransportRequests": "New Transport Requests",
    "myVehicles": "My Vehicles",
    "recentCompletedTrips": "Recent Completed Trips",
    "farmerLabel": "Farmer",
    "pickupLabel": "Pickup",
    "destinationLabel": "Destination",
    "vehicleLabel": "Vehicle",
    "viewVerification": "View Verification",
    "accept": "Accept",
    "available": "Available",
    "startTrip": "سفر شروع کریں",
    "reachedMandi": "منڈی پہنچ گئے",
    "completeTrip": "سفر مکمل کریں",
    "selectVehicleModalTitle": "Select Vehicle",
    "chooseVehicleSub": "Choose a vehicle for this transport request",
    "confirmBooking": "Confirm Booking",
    "farmerTrustVerifTitle": "Farmer Verification",
    "agrilinkTrustSub": "AgriLink Sewa Trust Verification",
    "farmDetails": "Farm Details",
    "trustStatusHigh": "Trust Status: HIGH",
    "trustDesc": "This booking request is from a verified farmer.",
    "closeVerification": "Close Verification Details",
    "truck": "Truck",
    "tractor": "Tractor / Trolley",
    "mini": "Mini Vehicle",
    "goodsTransport": "Goods Transport",
    "reqAcceptedSuccess": "Transport request accepted successfully!",
    "reqRejected": "Request rejected.",
    "tripStartedSuccess": "Trip started successfully!",
    "tripReachedSuccess": "Vehicle reached the procurement center!",
    "tripCompletedSuccess": "Trip completed successfully!",
    "bookingCreatedSuccess": "Booking created successfully!",
    "profileNotFound": "Account profile data not found! Please register.",
    "unauthorizedAccess": "Unauthorized Access: You do not have access to this portal."
  }
};

export function getLanguage() {
    return localStorage.getItem("agrilink_lang") || "en";
}

export function getT() {
    const lang = getLanguage();
    return translations[lang] || translations.en;
}

export function formatNumber(number) {
    const lang = getLanguage();
    const numMaps = {
        hi: "०१२३४५६७८९",
        mr: "०१२३४५६७८९",
        gu: "૦૧૨૩૪૫૬૭૮૯",
        bn: "০১২৩৪৫৬৭৮৯",
        as: "০১২৩৪৫৬৭৮৯",
        ta: "௦௧௨௩௪௫௬௭௮௯",
        te: "౦౧౨౩౪౫౬౭౮౯",
        kn: "೦೧೨೩೪೫೬೭೮೯",
        ml: "൦൧൨൩൪൫൬൭൮൯",
        pa: "੦੧੨੩੪੫੬੭੮੯",
        or: "୦୧୨୩୪୫୬୭୮୯",
        ur: "۰۱۲۳۴۵۶۷۸۹"
    };

    const map = numMaps[lang];
    if (!map) return String(number);

    return String(number).replace(/\d/g, (d) => map[Number(d)]);
}

export function changeLanguage(lang) {
    if (!lang) lang = getLanguage();
    localStorage.setItem("agrilink_lang", lang);

    // RTL Layout Switching for Urdu
    if (lang === "ur") {
        document.documentElement.dir = "rtl";
        document.documentElement.classList.add("rtl-mode");
    } else {
        document.documentElement.dir = "ltr";
        document.documentElement.classList.remove("rtl-mode");
    }

    const t = translations[lang] || translations.en;

    // Translate all elements with data-i18n
    document.querySelectorAll("[data-i18n]").forEach((el) => {
        const key = el.getAttribute("data-i18n");
        if (t[key]) {
            el.innerText = t[key];
        }
    });

    // Translate input placeholders with data-i18n-placeholder
    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
        const key = el.getAttribute("data-i18n-placeholder");
        if (t[key]) {
            el.placeholder = t[key];
        }
    });

    // Sync all language dropdowns on page
    document.querySelectorAll(".lang-select, #language, #langSwitcher, #languageSelect").forEach((select) => {
        if (select) select.value = lang;
    });

    // Dispatch event
    window.dispatchEvent(new CustomEvent("agrilink:languageChanged", { detail: { lang, t } }));
}

// Global initialization
if (typeof window !== "undefined") {
    window.changeLanguage = changeLanguage;
    window.getLanguage = getLanguage;
    window.getT = getT;
    window.formatNumber = formatNumber;
    window.supportedLanguages = supportedLanguages;

    document.addEventListener("DOMContentLoaded", () => {
        changeLanguage(getLanguage());
    });
}
